# Generated by Django 4.2.30 on 2026-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.FloatField()),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_status', models.CharField(choices=[('Overpriced', 'Overpriced'), ('Underpriced', 'Underpriced'), ('Fair', 'Fair')], default='Fair', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('images', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
