# Generated by Django 4.2.30 on 2026-07-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikelisting',
            name='variant_type',
            field=models.CharField(choices=[('Base', 'Base'), ('Mid', 'Mid'), ('Top', 'Top')], default='Base', max_length=20),
        ),
    ]
