# Generated by Django 4.2.30 on 2026-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file_ref', models.CharField(max_length=255)),
                ('riding_style', models.CharField(choices=[('Calm', 'Calm'), ('Moderate', 'Moderate'), ('Aggressive', 'Aggressive')], default='Calm', max_length=20)),
                ('suggestions', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
