# Generated by Django 4.2.30 on 2026-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('Chain Lube & Tension', 'Chain Lube & Tension'), ('Brake Pads Replacement', 'Brake Pads Replacement'), ('Tire Replacement', 'Tire Replacement'), ('Chain & Cassette Replacement', 'Chain & Cassette Replacement'), ('General Tuning & Safety Check', 'General Tuning & Safety Check')], max_length=100)),
                ('mileage', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
