# Generated by Django 4.2.30 on 2026-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='brand',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='model',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(choices=[('Chain Lube & Tension', 'Chain Lube & Tension'), ('Brake Pads Replacement', 'Brake Pads Replacement'), ('Tire Replacement', 'Tire Replacement'), ('Chain & Cassette Replacement', 'Chain & Cassette Replacement'), ('General Tuning & Safety Check', 'General Tuning & Safety Check'), ('Scheduled Service', 'Scheduled Service')], max_length=100),
        ),
    ]
